project_name: custom_linters
changelog:
  skip: true
builds:
  - id: custom_linters
    main: ./cmd/custom_linters/
    buildmode: plugin
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le
